<?php

namespace AppBundle\Repository;

/**
 * VodClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VodClassRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderByIdAsc(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:VodClass c ORDER BY c.id ASC'
            )
            ->getResult();
    }
}
