<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query;

/**
 * VodClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VodClassRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderByIdAsc(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:VodClass c ORDER BY c.id ASC'
            )
            ->getResult();
    }
    public function findAllClassToSelect(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c.id as id, c.name as text , c.parentId as parent,ABS(c.isLeaf-1) as disabled FROM AppBundle:VodClass c'
            )
            ->getResult(Query::HYDRATE_ARRAY );

    }
    public function getClassByIds($ids)
    {
        $qb =  $this->getEntityManager()->createQueryBuilder();
        $qb->from('AppBundle:VodClass','c')->select("c.name","c.id")->where($qb->expr()->in('c.id',$ids));
        $query = $qb->getQuery();
        $result = $query->getResult(Query::HYDRATE_ARRAY);
        return $result;
    }
    public function getClassIdsByParentId($parentId)
    {
        $qb =  $this->getEntityManager()->createQueryBuilder();
        $qb->from('AppBundle:VodClass','c')->select("c.id")->where('c.parentId = :parentId')->setParameter('parentId',$parentId);
        $query = $qb->getQuery();
        $result = $query->getResult(Query::HYDRATE_ARRAY);
        return $result;
    }
}
