<?php

namespace AppBundle\Repository;

/**
 * VodFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VodFileRepository extends \Doctrine\ORM\EntityRepository
{
}
