<?php

namespace AppBundle\Repository;

/**
 * VodListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VodListRepository extends \Doctrine\ORM\EntityRepository
{
}
