<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query;
use Symfony\Component\HttpKernel\Log\Logger;

/**
 * VodListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VodListRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchVod($search=array(),$offset=0,$limit=50,$orderField='v.id',$order='asc')
    {
        try{
            $qb = $this->getEntityManager()->createQueryBuilder();
//            $qb_count = $this->getEntityManager()->createQueryBuilder();
//            $qb_count->from('AppBundle:VodList','v')->leftJoin('AppBundle:VodClass','c','WITH','c.id=v.classId');
            $qb->from('AppBundle:VodList','v')->leftJoin('AppBundle:VodClass','c','WITH','c.id=v.classId');

            foreach($search as $key => $val){
                if(empty($val))
                {
                    continue;
                }
                switch ($key)
                {
                    case 'title':
                        $qb->andWhere('v.title like :title%');
                        $qb->setParameter('title',$val);
                        break;
                    case 'description':
                        $qb->andWhere('v.description like :description');
                        $qb->setParameter('description',$val);
                        break;
                    case 'classId':
                        $em = $this->getEntityManager();
                        $query = $em->createQuery('select c from AppBundle:VodClass c WHERE c.id =:class_id')->setParameter('class_id',$val);
                        $obj_class = $query->getSingleResult();
                        if($obj_class->getIsLeaf())
                        {
                            $qb->andWhere('v.classId = :classId');
                            $qb->setParameter('classId',$val);
                        }else{
                            $path = $obj_class->getPath().$obj_class->getId();
                            $qb->andWhere($qb->expr()->like('c.path',':path'));
                            $qb->setParameter('path',$path.',%');
                        }
                        break;
                    case 'status':
                        $qb->andWhere('v.status = :status');
                        $qb->setParameter('status',$val);
                        break;
                    case 'hls':
                        $qb->andWhere('v.toHls = :hls');
                        $qb->setParameter('hls',$val);
                        break;
                    default:
                        throw new \Exception('未知的查询字段');
                }
            }
            $qb->select($qb->expr()->countDistinct('v.id'));
            $count = $qb->getQuery()->getSingleScalarResult();

            $qb->select(array('v.id','v.title','v.description','v.playNum','4 as time','v.toHls','v.status','v.streams','v.creator','c.name as className','c.path as path','f.saveName'))->leftJoin('AppBundle:VodFile','f','WITH','f.id = v.videoId');
            $qb->setFirstResult($offset)->setMaxResults($limit);
            $qb->orderBy($orderField,$order);
            $query = $qb->getQuery();

            $result = $query->getResult(Query::HYDRATE_ARRAY);

            return array('total'=>$count,'rows'=>$result);

        }catch (\Exception $e){
            throw new \Exception($e->getMessage().'查询出错');
        }

    }
    public function getVodAndFileById($id)
    {
        try{
            $qb = $this->getEntityManager()->createQueryBuilder();

            $qb->from('AppBundle:VodList','v')->select(array('v.id','v.title','v.description','v.toHls','v.status','v.streams','v.creator','v.classId','f.id as fileId','f.name as fileName'))->leftJoin('AppBundle:VodFile','f','WITH','f.id = v.videoId');
            $qb->where('v.id = :id')->setParameter('id',$id);
            $query = $qb->getQuery();
            $result = $query->getSingleResult(Query::HYDRATE_ARRAY);
            return $result;
        }catch (\Exception $e){
            throw new \Exception($e->getMessage().'查询出错');
        }

    }
    public function getVodClassJoinClassByPublish()
    {
        try{
            $qb = $this->getEntityManager()->createQueryBuilder();

            $qb->from('AppBundle:VodList','v')
                ->select(array('c.id as classId','c.parentId','c.name','c.isLeaf'))
                ->leftJoin('AppBundle:VodClass','c','WITH','c.id = v.classId')
                ->groupBy('c.id')
                ->addGroupBy('c.parentId')
                ->orderBy('c.id')
                ->addOrderBy('c.parentId');
//                ->where('v.status = :status')
//                ->setParameter('status',"published");
            $query = $qb->getQuery();
            $result = $query->getResult(Query::HYDRATE_ARRAY);
            return $result;
        }catch (\Exception $e){
            throw new \Exception('-getVodClassJoinClassByPublish-'.$e->getMessage().'查询出错');
        }
    }
    public function getVodByClassIdAndLimit($id,$limit,$offset=0)
    {
        try{
            $qb = $this->getEntityManager()->createQueryBuilder();

            $qb->from('AppBundle:VodList','v')
                ->select(array('v.title','4 as time','v.playNum','v.id'))
                ->orderBy('v.id','desc')
//                ->where('v.status = :status')
//                ->setParameter('status',"closed")
                ->andWhere($qb->expr()->in('v.classId',$id))
                ->setFirstResult($offset)
                ->setMaxResults($limit);
            $query = $qb->getQuery();
            $result = $query->getResult(Query::HYDRATE_ARRAY);
            return $result;
        }catch (\Exception $e){
            throw new \Exception('-getVodByClassIdAndLimit-'.$e->getMessage().'查询出错');
        }
    }
    public function getVodCountByClassId($id)
    {
        try{
            $qb = $this->getEntityManager()->createQueryBuilder();
            $qb->from('AppBundle:VodList','v')
            ->select($qb->expr()->countDistinct('v.id'))
            ->where($qb->expr()->in('v.classId',$id));
            $count = $qb->getQuery()->getSingleScalarResult();
            return $count;
        }catch (\Exception $e){
            throw new \Exception('-getVodByClassIdAndLimit-'.$e->getMessage().'查询出错');
        }
    }
}
