<?php

namespace AppBundle\Repository;

/**
 * VodMd5FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VodMd5FileRepository extends \Doctrine\ORM\EntityRepository
{
}
