app:
    resource: '@AppBundle/Controller/HomeController.php'
    type: annotation
hello:
    path:       /hello
    defaults: { _controller: AppBundle:Hello:index }
app_login:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /
