default_create:
    path: /create
    defaults: { _controller: AppBundle:Default:create }
index:
    path:     /index
    defaults: { _controller: AppBundle:Hello:index }
login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
home_page:
    path: /
    defaults: { _controller: AppBundle:Home:index }
home_vod_list:
    path: /vod
    defaults: { _controller: AppBundle:VodShow:showVodList }
home_vod_item:
    path: /vod/item
    defaults: { _controller: AppBundle:VodShow:showVodItem }

admin_page:
    path: /admin/show
    defaults: { _controller: AppBundle:Admin:showIndex }
admin_vod_list:
    path: /vod/list
    defaults: { _controller: AppBundle:VodManage:showList }
admin_vod_list_data:
    path: /vod/search
    defaults: { _controller: AppBundle:VodManage:getListData}
admin_vod_add:
    path: /vod/add
    defaults: { _controller: AppBundle:VodManage:addVod }
admin_class_show:
    path: /class/show
    defaults: { _controller: AppBundle:ClassManage:show }
login_check:
    path: /login_check
logout:
    path: /logout

show_list:
    path:     /showList
    defaults: { _controller: AppBundle:VodManage:showList }

show:
    path:     /show
    defaults: { _controller: AppBundle:ClassManage:show }
