default_create:
    path: /create
    defaults: { _controller: AppBundle:Default:create }
index:
    path:     /index
    defaults: { _controller: AppBundle:Hello:index }
login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
#-------------------------首页显示---------------------------------
home_page:
    path: /
    defaults: { _controller: AppBundle:Home:index }
#----------------------------点播显示--------------------------------
home_vod_list:
    path: /vod
    defaults: { _controller: AppBundle:VodShow:showVodList }
home_vod_item:
    path: /vod/item
    defaults: { _controller: AppBundle:VodShow:showVodItem }
#-----------------------------管理后台主页---------------------------
admin_page:
    path: /admin
    defaults: { _controller: AppBundle:Admin:showIndex }
#-----------------------------点播管理-------------------------------
admin_vod_show:
    path: /vod/show
    defaults: { _controller: AppBundle:VodManage:show }
admin_vod_data:
    path: /vod/search
    defaults: { _controller: AppBundle:VodManage:getData}
admin_vod_add:
    path: /vod/add
    defaults: { _controller: AppBundle:VodManage:addVod }
admin_vod_add_show:
    path: /vod/add/show
    defaults: { _controller: AppBundle:VodManage:showAdd }
admin_vod_upload:
    path: /vod/upload
    defaults: { _controller: AppBundle:VodManage:upLoad }

#-----------------------------分类管理-------------------------------
admin_class_show:
    path: /class/show
    defaults: { _controller: AppBundle:ClassManage:show }
admin_class_add:
    path: /class/add
    defaults: { _controller: AppBundle:ClassManage:add }
admin_class_data:
    path: /class/getData
    defaults: { _controller: AppBundle:ClassManage:getData }
admin_class_delete:
    path: /class/delete
    defaults: { _controller: AppBundle:ClassManage:delete}
admin_class_edit:
    path: /class/edit
    defaults: { _controller: AppBundle:ClassManage:edit}
#----------------------------登录-----------------------
login_check:
    path: /login_check
logout:
    path: /logout
