parameters:
    task:
        checkUpload: "task.check_upload"
        mergeChunk: "task.merge_chunk"
        hlsVod: "task.hls_vod"
services:
#    app.example:
#        class:     AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#        calls:
#            - [setService, ["@service_id"]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    task.check_upload:
        class:  AppBundle\Service\Task\CheckUpload
        public: true
        arguments:
            - '@service_container'
    task.merge_chunk:
        class:  AppBundle\Service\Task\MergeChunk
        public: true
        arguments:
            - '@service_container'
    task.hls_vod:
        class:  AppBundle\Service\Task\HlsVod
        public: true
        arguments:
            - '@service_container'
