AppBundle\Entity\MiUser:
    type: entity
    table: user
    repositoryClass: AppBundle\Repository\MiUserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        account:
            type: string
            length: 128
            nullable: false
        email:
            type: string
            length: 128
            nullable: false
        password:
            type: string
            length: 64
            nullable: false
        salt:
            type: string
            length: 32
            nullable: false
        type:
            type: smallint
            length: 6
            nullable: false
            options:
                unsigned: true
                default: 2
        mi_account_id:
            type: integer
            length: 11
        create_time:
            type: datetime
            nullable: false
        modified_time:
            type: datetime
            nullable: false
#    lifecycleCallbacks: {  }
