AppBundle\Entity\VodClass:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\VodClassRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: false
            unique: true
        parentId:
            type: integer
            nullable: false
            column: parent_id
        path:
            type: string
            length: 255
        createTime:
            type: datetimetz
            nullable: false
            column: create_time
            gedmo:
                 timestampable:
                     on: create
        modifiedTime:
            type: datetimetz
            nullable: false
            column: modified_time
            gedmo:
                 timestampable:
                    on: update
        isLeaf:
            type: boolean
            nullable: false
            column: is_leaf
    lifecycleCallbacks: { }
