AppBundle\Entity\VodList:
    type: entity
    table: vod_list
    repositoryClass: AppBundle\Repository\VodListRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        status:
            type: string
            length: 255
            options:
                default: 'closed'
        pictureUrl:
            type: string
            length: 255
            column: picture_url
        streams:
            type: string
            length: 255
        creator:
            type: integer
            nullable: true
        videoId:
            type: integer
            nullable: true
        createTime:
            type: datetimetz
            nullable: false
            column: create_time
            gedmo:
                 timestampable:
                      on: create
        modifiedTime:
            type: datetimetz
            nullable: false
            column: modified_time
            gedmo:
                 timestampable:
                    on: update
        classId:
            type: integer
            nullable: false
            column: class_id
        playNum:
            type: integer
            nullable: true
            column: play_num
            options:
                default: 0
        originUrl:
            type: string
            length: 255
            column: origin_url
        mediaName:
            type: string
            length: 255
            column: media_name
            options:
                default: ''
        mediaUrl:
            type: string
            length: 255
            column: media_url
            options:
                default: ''
        toHls:
            type: boolean
            column: to_hls
            options:
              default: 0
    lifecycleCallbacks: {  }
